subdirectory = $(patsubst %/module.mk,%, \
	$(word $(words $(MAKEFILE_LIST)),$(MAKEFILE_LIST)))



TARGETS          :=
DEPENDS          :=

# System variables.
ARCH             := $(shell arch)
OS               := $(shell uname)

# Global variables.
PRJ_ROOT         := .
SUBMAKEFILES     := $(shell find . -name module.mk)

# Complier and linker
COMPLIER         := g++ -std=c++11
COMPLIER_OPTIONS := -Wall -Wextra -Werror
ifdef DEBUG
    COMPLIER_OPTIONS += -g
endif
LINKER           := g++ -std=c++11
LINKER_OPTIONS   := -Wl,-rpath,$(PROJECT_ROOT)/libs

# Commands
RM               := rm -rf
SED              := sed
MV               := mv
AR               := ar

help:
	@echo
	@echo "make all       - Build all projects."
	@echo "make <project> - Build specific project, project will be the directory name in projects directory."
	@echo "make clean     - Remove files generated by make."
	@echo "make tarball   - To create a release tarball."

include $(SUBMAKEFILES)

.PHONY: all
all: $(TARGETS)

.PHONY: clean
clean:
	@find . -name '*.o' -exec $(RM) {} \;
	@find . -name '*.d' -exec $(RM) {} \;
	@$(RM) ./bin/*

.PHONY: tarball
tarball:
	@echo tarball


