# System variables.
ARCH             := $(shell arch)
OS               := $(shell uname)

# Complier and linker
COMPLIER         := g++ -std11
COMPLIER_OPTIONS := -Wall -Wextra -Werror
LINKER           := g++ -std11
LINKER_OPTIONS   :=

# Commands
RM               := rm -rf

# Global variables.
SUBMAKEFILES     := $(shell find . -name module.mk)

help:
	@echo
	@echo "make all       - Build all projects."
	@echo "make <project> - Build specific project, project will be the directory name in projects directory."
	@echo "make clean     - Remove files generated by make."
	@echo "make tarball   - To create a release tarball."





.PHONY: all
all:


.PHONY: clean
clean:
	@find . -name '*.o' -exec $(RM) {} \;
	@find . -name '*.d' -exec $(RM) {} \;
	@$(RM) ./bin/*

.PHONY: tarball
tarball:
	@echo tarball
