FILE(GLOB LIBUTIL_HEADERS ${PROJECT_SOURCE_DIR}/base/util/inc)

FIND_PATH(UTIL_INCLUDE_DIR LIBUTIL_HEADERS ${PROJECT_SOURCE_DIR}/base/util/inc)
FIND_LIBRARY(UTIL_LIBRARY NAMES libutil.a PATHS ${PROJECT_BINARY_DIR}/lib)

IF (UTIL_LIBRARY AND UTIL_INCLUDE_DIR)
   SET(UTIL_FOUND TRUE)
ENDIF (UTIL_LIBRARY AND UTIL_INCLUDE_DIR)

IF (UTIL_FOUND)
   IF (NOT UTIL_FIND_QUIETLY)
      MESSAGE(STATUS "FOUND UTIL: ${UTIL_LIBRARY}")
   ENDIF (NOT UTIL_FIND_QUIETLY)
ELSE (UTIL_FOUND)
   IF (UTIL_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "CANNOT FIND UTIL LIBRARY")
   ENDIF (UTIL_FIND_REQUIRED)
ENDIF (UTIL_FOUND)
